all:
	g++ -Wall -Wextra -std=c++11 driver.cpp Product.cpp Product.h Layout.h ScreenLayout.cpp ScreenLayout.h WebLayout.cpp WebLayout.h View.h ManagerView.cpp ManagerView.h CustomerView.cpp CustomerView.h -o driver

clean:
	rm *o driver